export * from './CategoriesPage/Categories';
export * from './CharactersPage/Characters';
export * from './FilmsPage/Films';
export * from './SpeciesPage/Species';
export * from './StarShipsPage/StarShips';
export * from './VehiclesPage/Vehicles'
export * from './PlanetsPage/Planets';
export * from './CharacterPage/Character';
export * from './FilmPage/Film';
export * from './SpeciePage/Specie';
export * from './StarShipPage/StarShip';
export * from './VehiclePage/Vehicle';
export * from './PlanetPage/Planet';
export * from './HomePage/Home';
export * from './FavoritesPage/Favorites';
export * from './SearchPage/Search';
export * from './NotFoundPage/NotFound';
export * from './RegisterPage/Register';